### ISSUE TITLE
Values not showing

### ISSUE THREAD

**Issue by prahastagiri** [TKJElectronics/KalmanFilter#11]
Hi, i'am trying to run your code but after i uploaded it on my NodeMCU and my question is is the code already been calibrated? how to make it to show values around 0?

i am using arduinoIDE ver.1.8.9
NodeMCU 1.0 esp8266

**Comment by Lauszus** [comment]
Check out how I do it with for my flight controller: https://github.com/Lauszus/LaunchPadFlightController/blob/91611708c9f801f9d66b73085ac6c465818907ff/src/MPU6500.c#L109-L169.
