### ISSUE TITLE
i2cWrite fail : 4

### ISSUE THREAD

**Issue by haarislabs** [TKJElectronics/KalmanFilter#12]
I sometimes get this error [error info attached in the screeshot] while reading the values of my MPU6050 sensor. I'm using an ESP8266, even after resetting the board it shows the same error, but if I unplug the the power source and put it back on then it works fine. What causes this error and how can I avoid it ???

![screenshot 39](https://user-images.githubusercontent.com/34370480/41034784-5127c1a6-69a8-11e8-8674-4daa9828eb8a.png)

**Comment by rocheparadox** [comment]
Either your wire connection is not solid(i.e loosely fit) or your MPU6050 has failed. Elements on the module are SMDs you know. They have to be handled with care. I had the same problem with one of my MPU6050s. It would show some erratic value for sometime and then show the same error message as yours.

**Comment by Lauszus** [comment]
As @rocheparadox wrote the "i2cWrite failed" warning is probably a bad connections. Please make sure that you have a soldered connecting between the IMU and ESP8266.

**Comment by haarislabs** [comment]
Thanks :)
