### ISSUE TITLE
print data in Serial moniter 

### ISSUE THREAD

**Issue by avsingh999** [TKJElectronics/KalmanFilter#13]
when I open it then it's show these type data  help me

![screenshot 3](https://user-images.githubusercontent.com/25536022/41038425-b1bab82e-69b3-11e8-8a6f-0896c78d6167.png)

**Comment by Lauszus** [comment]
Please set the serial monitor baud rate to 115200.

**Comment by avsingh999** [comment]
thank you @Lauszus
