### ISSUE TITLE
How is your MPU connected to your arduino?

### ISSUE THREAD

**Issue by DimitrijeK** [TKJElectronics/KalmanFilter#15]
I ran the code but I got "Error reading sensor" so I assume that wiring is the problem. Right now I have this:

A4 -> SDA
A5 -> SCL
GND -> GND
5V -> VCC

**Comment by Lauszus** [comment]
I assume you are using some kind of breakout board? Please double check that it has an voltage regulator on the breakout board, as the MPU does not support 5V.

Please also connect AD0 to GND.

If that still does not work, then add some pull-up resistor on the SDA and SCL signals.
