### ISSUE TITLE
interrupt pin needed? which pin on Uno, Mega, Due, Zero, ESP8266?

### ISSUE THREAD

**Issue by dsyleixa** [TKJElectronics/KalmanFilter#16]
hi,
I don't find a documentation about if there is an interrupt pin needed? 
In case, which pin on Uno, Mega, Due, Zero, ESP8266? All the same or divergent?

**Comment by Lauszus** [comment]
No. It's a very simply example, so the INT pin is not used.

I would recommend using the INT pin if you can not use delays in your code. For instance check out the following code where I use the INT pin: https://github.com/Lauszus/OneWheeledSkateboard.

**Comment by dsyleixa** [comment]
thanks, I have repetitive readings in my loop(), I actually don't need Intrs, so I'm fine with that.
I just was missing an explicite hint here in theis repo.
Thanks for your reply!
