### ISSUE TITLE
how to retrieve relative heading = yaw ?

### ISSUE THREAD

**Issue by dsyleixa** [TKJElectronics/KalmanFilter#19]
hi
how is it possible to retrieve relative heading = yaw ?

**Comment by dsyleixa** [comment]
will there be a way to get yaw here in the future?

**Comment by dsyleixa** [comment]
is this repository no longer maintained for issues and requests?

**Comment by Lauszus** [comment]
No not with this particular code, but you could follow the same principals as described in the blog post: http://blog.tkjelectronics.dk/2012/09/a-practical-approach-to-kalman-filter-and-how-to-implement-it/ and then apply it to your own application. That's the beauty of the Kalman filter.

Anyway check out the code for my flight controller, as calculate the yaw there as well. The relevant code is here: https://github.com/Lauszus/LaunchPadFlightController/blob/master/src/IMU.c.

**Comment by dsyleixa** [comment]
thanks, I checked that but con't find any relevant code snippets.
Can you please copy and paste them?

**Comment by dsyleixa** [comment]
thanks, I checked that but can't find any relevant code snippets about yaw (mind you, no magnetometer for that, just gyros and accel!), and the native Kalman maths is far beyond my skills.
So could you please copy and paste the function code  from your  flight controller?

BTW, as the issue is not resolved yet, would you please reopen this issue? Finally it's an enhancement request.
