### ISSUE TITLE
How do you fuse encoder and gyro?

### ISSUE THREAD

**Issue by 3038922** [TKJElectronics/KalmanFilter#21]
I have a four-wheeled robot.
There's an encoder on each side, and a gyroscope.
I use the formula:"(encL - encR) / 2.0 * _turnScale" can get an angle.
Considering the problem of wheel skidding and gyroscope self-increasing, I want to integrate them.
The two values I get are both angular values, not angular velocities. I set a 10MS loop once.

**Comment by Theara-Seng** [comment]
@3038922  can I see the code of you for fuse encoder and gyro
