### ISSUE TITLE
Method Kalman.getAngle()

### ISSUE THREAD

**Issue by darlandc1998** [TKJElectronics/KalmanFilter#24]
Hello, I'm in doubt when returning the following method:

`float Kalman::getAngle(float newAngle, float newRate, float dt);`

I understand that by parameter, an angle (degrees), an angular rate (degrees/seconds) and time (seconds) are passed. Is the return of this method an angle estimate in degrees? Or an angular rate in degrees per second?

Thank you!

**Comment by Lauszus** [comment]
@darlandc1998 yes the returned angle is in degrees.

**Comment by darlandc1998** [comment]
Thank you!
