### ISSUE TITLE
Arduino Specific or General C++?

### ISSUE THREAD

**Issue by usmanmehmood55** [TKJElectronics/KalmanFilter#26]
Hi. 
I'm looking at your library and it seems to be in general C++ (doesn't have Arduino specific code). I just wanted to confirm if this is the case, since I want to use it with a different microcontroller and I'm not using the Arduino framework in it.
Your help would be much appreciated.

**Comment by Lauszus** [comment]
Yes you can use it with any microcontroller you like. Simply just download the files and include them in your project.
