### ISSUE TITLE
tag 1.0.1 has library.properties with version 1.0.0

### ISSUE THREAD

**Issue by ffissore** [TKJElectronics/KalmanFilter#4]
Thus leading to a double entry in http://downloads.arduino.cc/libraries/library_index.json

**Comment by ffissore** [comment]
See https://github.com/arduino/Arduino/issues/2983

**Comment by Lauszus** [comment]
@ffissore hmm it doesn't look like it removes the duplicate automatically: http://downloads.arduino.cc/libraries/library_index.json. Also the version parameter isn't updated? Note how the url is updated correctly, but the version parameter is still 1.0.0.

**Comment by ffissore** [comment]
I guess it's because it hasn't used the new tag but it's still stuck with the older. I'm out of the office until next wednesday.

**Comment by ffissore** [comment]
In the meanwhile, I'll reopen https://github.com/arduino/Arduino/issues/2983

**Comment by Lauszus** [comment]
Okay thanks.
